# Generated by Django 4.0.3 on 2022-03-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
