# Generated by Django 4.0.3 on 2022-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_super_user',
            field=models.BooleanField(default=False),
        ),
    ]
