# Generated by Django 4.0.3 on 2022-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='comment',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
