# Generated by Django 4.0.3 on 2022-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_queries_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='document_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
