# Generated by Django 4.0.3 on 2022-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_queries_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
