# Generated by Django 4.0.3 on 2022-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_queries_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='status_check',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
