# Generated by Django 4.0.3 on 2022-05-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_requirement_balance_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='comment',
        ),
    ]
